import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Providers from "./Providers";
import { StoreProvider } from "./StoreProvider";
import PathnameWrapper from "@/components/PathnameWrapper";
import AuthBootstrap from "@/components/auth/AuthBootstrap";

const plus_jakarta_sans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-plus-jakarta-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${plus_jakarta_sans.className} antialiased`}>
        <StoreProvider>
          <AuthBootstrap>
            <Providers>
              <PathnameWrapper>
                <main>{children}</main>
              </PathnameWrapper>
            </Providers>
          </AuthBootstrap>
        </StoreProvider>
      </body>
    </html>
  );
}
